# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: /ko/
    weight: 10
  
  - name: 소개
    weight: 15
    hasChildren: true
  - parent: 소개
    name: 자기소개 요약
    url: /ko/#profile_intro/
  - parent: 소개
    name: 자기소개
    url: /ko/about/
  
  - name: 주요 역량
    url: /ko/#features/
    weight: 20
 
  - name: 프로젝트
    weight: 30
    hasChildren: true
  - parent: 프로젝트
    name: 프로젝트 소개
    url: /#projects
  - parent: 프로젝트
    name: 프로젝트1
    url: project/p1/
  - parent: 프로젝트
    name: 프로젝트2
    url: project/p2/
  - parent: 프로젝트
    name: 프로젝트3
    url: project/p3/
  
  - name: 연락처
    url: /ko/contact/
    weight: 40
