main:
  - name: Home
    url: /en/
    weight: 10
  
  - name: About
    weight: 15
    hasChildren: true
  - parent: About
    name: About Me
    url: /en/about/
  
  - name: Key Skills
    url: /en/#features/
    weight: 20
 
  - name: Projects
    weight: 30
    hasChildren: true
  - parent: Projects
    name: Project 1
    url: /en/project/p1/
  - parent: Projects
    name: Project 2
    url: /en/project/p2/
  - parent: Projects
    name: Project 3
    url: /en/project/p3/
  
  - name: Contact
    url: /en/contact/
    weight: 40
