# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Main
    url: /en/
    weight: 10
  - name: Publications
    url: /en/publications/
    weight: 11
  - name: Talks
    url: /en/events/
    weight: 12
  - name: News
    url: /en/blog/
    weight: 13
  - name: Experience
    url: /en/experience/
    weight: 20
  - name: Projects
    url: /en/projects/
    weight: 30
